#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-redcarpet
Version  : 3.3.4
Release  : 8
URL      : https://rubygems.org/downloads/redcarpet-3.3.4.gem
Source0  : https://rubygems.org/downloads/redcarpet-3.3.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: rubygem-redcarpet-bin
Requires: rubygem-redcarpet-lib
BuildRequires : gmp-dev
BuildRequires : ruby
BuildRequires : rubygem-rake-compiler
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks
BuildRequires : rubygem-test-unit

%description
Redcarpet is written with sugar, spice and everything nice
============================================================

%package bin
Summary: bin components for the rubygem-redcarpet package.
Group: Binaries

%description bin
bin components for the rubygem-redcarpet package.


%package lib
Summary: lib components for the rubygem-redcarpet package.
Group: Libraries

%description lib
lib components for the rubygem-redcarpet package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n redcarpet-3.3.4
gem spec %{SOURCE0} -l --ruby > rubygem-redcarpet.gemspec

%build
export LANG=C
gem build rubygem-redcarpet.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
redcarpet-3.3.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/redcarpet-3.3.4
ruby -v -I.:lib:test test*/test_*.rb
ruby -v -I.:lib:test test*/*_test.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/redcarpet-3.3.4.gem
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.3.4/gem.build_complete
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.3.4/gem_make.out
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/README.markdown
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/bin/redcarpet
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/.RUBYARCHDIR.time
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/Makefile
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/autolink.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/autolink.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/autolink.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/buffer.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/buffer.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/buffer.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/houdini.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/houdini_href_e.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/houdini_href_e.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/houdini_html_e.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/houdini_html_e.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/html.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/html.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/html.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/html_blocks.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/html_smartypants.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/html_smartypants.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/markdown.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/markdown.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/markdown.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/rc_markdown.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/rc_markdown.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/rc_render.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/rc_render.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/redcarpet.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/stack.c
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/stack.h
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/stack.o
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/lib/redcarpet.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/lib/redcarpet/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/lib/redcarpet/compat.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/lib/redcarpet/render_man.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/lib/redcarpet/render_strip.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/redcarpet.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/custom_render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/fixtures/benchmark.md
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/html5_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/html_render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/html_toc_render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/markdown_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/pathological_inputs_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/redcarpet_bin_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/redcarpet_compat_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/safe_render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/smarty_html_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/smarty_pants_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/stripdown_render_test.rb
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/test/test_helper.rb
/usr/lib64/ruby/gems/2.3.0/specifications/redcarpet-3.3.4.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/redcarpet

%files lib
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/redcarpet-3.3.4/redcarpet.so
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/ext/redcarpet/redcarpet.so
/usr/lib64/ruby/gems/2.3.0/gems/redcarpet-3.3.4/lib/redcarpet.so
